### ISSUE TITLE
Requested changes / issue notices in wrapper

### ISSUE THREAD

**Issue by Hopefuls** [Bensonheimer992/LicenseGate-JS-Wrapper#1]
Heya, as mentioned on discord already, compiled here:

- There is a deprecation notice when using the crypto library, as it is a built-in module now (as of node v20.11.0 and npm v10). If your library has a version requirement, note that in the readme too (aswell as the package.json, unsure how npm does that)
- There is a functional difference between using the LicenseGate constructor and the `setPublicRsaKey` when trying to use challenge signing: setPublicRsaKey does not set `useChallenge` while the constructor does, thus doesn't work to sign a challenge. Ensure they're functionally equal (such as by calling `useChallenge` by the constructor when the RsaKey is set, aswell as when invoking `setPublicRsaKey`).
- Challenge signing does not work, as you're removing the important start and end-indicators of the rsa key, causing the verification to fail: https://github.com/Bensonheimer992/LicenseGate-JS-Wrapper/blob/4538709180113a570f20abc7c2c9d29d227f8d79/src/index.ts#L130
```
Error: error:1E08010C:DECODER routines::unsupported
    at Verify.verify (node:internal/crypto/sig:224:24)
    at _LicenseGate.verifyChallenge (/home/licensegatejstest/node_modules/licensegate/dist/index.js:146:21)
    at _LicenseGate.verify (/home/licensegatejstest/node_modules/licensegate/dist/index.js:103:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async checkLicense (/home/licensegatejstest/src/index.js:11:18) {
  library: 'DECODER routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_UNSUPPORTED'
}
```
- Suggestion: Change the user-agent to something recognizable, such as `Bensonheimer992/LicenseGate-JS Wrapper`:
https://github.com/Bensonheimer992/LicenseGate-JS-Wrapper/blob/4538709180113a570f20abc7c2c9d29d227f8d79/src/index.ts#L116
- Suggestion: Switch the readme-example to english ;)

Once these are done, I'm glad to include the library in the docs. Thank you!

**Comment by Bensonheimer992** [comment]
Ok thanks im working on it

**Comment by Bensonheimer992** [comment]
ok @Hopefuls  i think i fixed all of this

**Comment by Hopefuls** [comment]
Yup looks good, a few more things to please change in your examples from the readme:

- your README shows the examples with using the rsa keys, though your example would not function as to how your code is handling that setRSAKey: Either correct it to also enable "useChallenges" within your code or change it accordingly in the readme that you should also use "useChallenges" when using setRSAKey.

- also:
```js
  const userId = 'Your UserID';
  const licenseKey = 'Your LicenseKey';
  const publicRSAKey = 'Your RSA Key'
  ```
  Please be consistent with the syntax, in this case the missing semicolon on the last one.

Thank you.

**Comment by Bensonheimer992** [comment]
Ok. The ReadME is changed

**Comment by Hopefuls** [comment]
Change doesn't match what you have in your source code, useChallenges doesn't have any parameters
